apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app-1
  template:
    metadata:
      labels:
        app: sample-app-1
    spec:
      containers:
      - name: sample-app-1
        image: 888154844094.dkr.ecr.us-east-1.amazonaws.com/jenkins-2801:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-service-1
spec:
  type: LoadBalancer
  selector:
    app: sample-app-1
  ports:
    - port: 80
      targetPort: 80
